replicaCount: 2
image:
  backend: samfoul/backend-k8s:v3
  frontend: samfoul/frontend-k8s:v5
resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
ingress:
  host: "172.18.255.200" # Ton IP MetalLB
